project_id = "dhuldgnqxistajvuwgao"

[functions.send-notification]
verify_jwt = false

[functions.check-overdue-invoices]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.create-payment-link]
verify_jwt = false

[functions.generate-recurring-invoices]
verify_jwt = false
