project_id = "dhuldgnqxistajvuwgao"

# Authenticated functions - require JWT
[functions.create-payment-link]
verify_jwt = true

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.audit-log]
verify_jwt = true

# Public functions - no JWT required
[functions.client-portal]
verify_jwt = false

[functions.auth-secure-signup]
verify_jwt = false

# System functions - require cron/system secret
[functions.send-notification]
verify_jwt = false

[functions.check-overdue-invoices]
verify_jwt = false

[functions.generate-recurring-invoices]
verify_jwt = false
